### PR TITLE
Prepare inGenerator release

### PR DESCRIPTION
**Pull request by craig410**
- [x] ~~Make tests pass on PHP 7.4~~
 - [x] Test on PHP 8.0, 8.1 & 8.2
 - [x] Update README
 - [x] Update composer.json before releasing

### CODE REVIEW

**Comment by acoulton** [comment]
@craig410 I think this is probably ready for me to merge it, get it on packagist, and cut a 1.0.0-alpha release that we can test on our projects, unless you have any concerns?

**Comment by craig410** [comment]
I'll have a look this evening

**Comment by craig410** [comment]
@acoulton LGTM

**Comment by acoulton** [comment]
Whoops, meant to retarget to 1.x will fix that later

**Pull request merged**
